# Generated by Django 4.1.5 on 2023-10-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_nombreusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsuari',
            new_name='idUsuario',
        ),
    ]
