# Generated by Django 4.2.6 on 2023-11-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Asignatura')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla de Asignatura')),
                ('seccion', models.CharField(max_length=10, verbose_name='Sección de Asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.asignatura', verbose_name='Asignaturas asociadas'),
        ),
    ]
