# Generated by Django 4.1.5 on 2023-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_idusuari_usuario_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Categoria',
            field=models.CharField(max_length=50, verbose_name='Nombre de Categoria'),
        ),
    ]
