# Generated by Django 4.2.6 on 2023-11-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asignatura',
            field=models.CharField(max_length=50, verbose_name='Contraseña de usuario'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.CharField(max_length=50, verbose_name='Nombre de usuario'),
        ),
    ]
