# Generated by Django 4.2.6 on 2023-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_asistencia_asignatura_alter_asistencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asignatura',
            field=models.CharField(max_length=50, verbose_name='Asignatura'),
        ),
    ]
